
<form action="/completarInfo" method="POST" class="text-center">
    <h1 >Informações Adicionais</h1>
    <p>Acesse suas configurações do usuario, para alterar qualquer dado</p>
    <div class="img-wrapper">
        <img src="img/perfilNoUser.png">
    </div>
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <label for="nome" class="input-group-text" id="basic-addon1">Nome</label>
        </div>
        <input type="text" class="form-control" value="<?php echo $this->view->info['nome'] ; ?>" name="nome" id="nome" required>
    </div>
    
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <label for="telefone" class="input-group-text" id="basic-addon1">Telefone</label>
        </div>
        <input type="tel" class="form-control" value="<?php echo $this->view->info['telefone'] ; ?>" name="telefone" id="telefone" required>
    </div>
    <div class="btnGroup d-flex justify-content-center align-items-center mt-5 position-absolute">
        <button type="submit" class="btn btn-danger mr-3"><i class="fa-solid fa-xmark"></i></button>
        <button type="camcel" class="btn btn-success mr-3"><i class="fa-solid fa-angles-right"></i></button>
    </div>
</form>