<?php 


?>
<!DOCTYPE html>
<html lang="pt-br">
	<head>
		<!-- TITLE -->
		<title>Whatsapp</title>

		<!-- META -->
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="Whatsapp_Clone">
		<meta name="keywords" content="HTML, CSS, JavaScript, PHP, SQL, MYSQL, BOOTSTRAP">
		<meta name="author" content="Lurique">

		<!-- CSS -->
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
		<link rel="stylesheet" href="https://necolas.github.io/normalize.css/8.0.1/normalize.css">
		<link rel="stylesheet" href="css/registroStyle.css">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
		<link rel="stylesheet" href="./css/style.css">
		<!-- <link rel="stylesheet" href="path/to/intlTelInput.css"> -->

		<!-- JS -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
		<script src="js/search.js" defer ></script>
		<script src="js/addNumber.js" defer></script>
		<script src="js/notfy.js" defer></script>

		<!-- FAVICO -->
		<link rel="shortcut icon" href="ico/favicon.ico" type="image/x-icon">
		<link rel="apple-touch-icon" sizes="180x180" href="ico/apple-touch-icon.png">
		<link rel="icon" type="image/png" sizes="32x32" href="ico/favicon-32x32.png">
		<link rel="icon" type="image/png" sizes="16x16" href="ico/favicon-16x16.png">
		<link rel="manifest" href="ico/site.webmanifest">

	</head>

	<body>
		<?= $this->content() ?>
	</body>

</html>