    <?php
        // echo '<pre>';
        // var_dump($this->view->notfy);
        // echo '</pre>';
        
    ?>
    <main>
        <section class="menuWhatsApp">

            <header class="menuPerfil">
                <div class="perfilImagem">
                    <?php if(empty($_SESSION['img'])){?>
                        <img src="img/perfilNoUser.png">
                    <?php }else{ ?>
                        <img src="<?php echo $_SESSION['img'];?>">
                    <?php }?>
                </div>
                <div class="perfilConfig">
                    <ul>
                        <Li><i class="fa-solid fa-spinner"></i></Li>
                        <li>
                            <i class="fa-solid fa-message"></i>
                        </li>
                        <li onclick="addNumber()"><i class="fa-solid fa-plus"></i></li>
                        <li id="openMenu"><i class="fa-solid fa-ellipsis-vertical"></i></li>
                        <li id="sair"><a href="/sair"><i class="fa-solid fa-door-closed"></i></i></a></li>
                    </ul>
                    
                </div>
            </header>

            <div class="adicionarContato onFocus">
                <form id="criarContato">
                    <p>
                        <select name="codigoPais" id="codigoPais" class="onFocus" onchange="activeClass(this)">
                            <option value="">DDI</option>
                            <option value="55">+55</option>
                        </select>
                            <select name="codigoEstado" id="codigoEstado" class="onFocus" onchange="activeClass(this)">
                            <option value="">(DDD)</option>
                            <option value="11">(11)</option>
                            <option value="12">(12)</option>
                            <option value="13">(13)</option>
                            <option value="14">(14)</option>
                            <option value="15">(15)</option>
                            <option value="16">(16)</option>
                            <option value="17">(17)</option>
                            <option value="18">(18)</option>
                            <option value="19">(19)</option>
                            <option value="21">(21)</option>
                            <option value="22">(22)</option>
                            <option value="24">(24)</option>
                            <option value="27">(27)</option>
                            <option value="28">(28)</option>
                            <option value="31">(31)</option>
                            <option value="32">(32)</option>
                            <option value="33">(33)</option>
                            <option value="34">(34)</option>
                            <option value="35">(35)</option>
                            <option value="37">(37)</option>
                            <option value="38">(38)</option>
                            <option value="41">(41)</option>
                            <option value="42">(42)</option>
                            <option value="43">(43)</option>
                            <option value="44">(44)</option>
                            <option value="45">(45)</option>
                            <option value="46">(46)</option>
                            <option value="47">(47)</option>
                            <option value="48">(48)</option>
                            <option value="49">(49)</option>
                            <option value="51">(51)</option>
                            <option value="53">(53)</option>
                            <option value="54">(54)</option>
                            <option value="55">(55)</option>
                            <option value="61">(61)</option>
                            <option value="62">(62)</option>
                            <option value="64">(64)</option>
                            <option value="63">(63)</option>
                            <option value="65">(65)</option>
                            <option value="66">(66)</option>
                            <option value="67">(67)</option>
                            <option value="68">(68)</option>
                            <option value="69">(69)</option>
                            <option value="71">(71)</option>
                            <option value="73">(73)</option>
                            <option value="74">(74)</option>
                            <option value="75">(75)</option>
                            <option value="77">(77)</option>
                            <option value="79">(79)</option>
                            <option value="81">(81)</option>
                            <option value="82">(82)</option>
                            <option value="83">(83)</option>
                            <option value="84">(84)</option>
                            <option value="85">(85)</option>
                            <option value="86">(86)</option>
                            <option value="87">(87)</option>
                            <option value="88">(88)</option>
                            <option value="89">(89)</option>
                            <option value="98">(98)</option>
                            <option value="99">(99)</option>                                
                            <option value="96">(96)</option>
                            <option value="92">(92)</option>
                            <option value="97">(97)</option>
                            <option value="91">(91)</option>
                            <option value="93">(93)</option>
                            <option value="94">(94)</option>
                            <option value="95">(95)</option>
                        </select>                            
                        <input type="number" name="numero" class="onFocus" id="numero" placeholder="Insira o seu numero de telefone" onchange="activeClass(this)" maxlength="9">
                        <input type="hidden" name="telefone" id="telefone" value="<?php echo $_SESSION['telefone']; ?>">
                        <button class="onFocus" id="addNumber">Adicionar</button>
                    </p>
                </form>
            </div>

            <div class="notificacao">
                <ul>
                    <li class="select" id="recieve" onclick=" recieve()">
                        Solicitações Recebidas
                    </li>

                    <li id="send" onclick="send()">
                        Solicitações Enviadas
                    </li>
                </ul>
                <div class="cardGroup">
                    
                </div>
            </div>
            


            <div class="menuConversas">
                <div class="conversasSearch">
                    <p>
                        <i class="fa-solid fa-magnifying-glass using" id="search" onclick="location.href='#'"></i>
                        <i class="fa-solid fa-arrow-left-long" id="back"></i>
                        <input onfocus="MudarClassP(this)" onblur="VoltarClassP(this)" type="search" placeholder="Pesquisar ou começar uma nova conversa" id="searchConversas">
                    </p>
                </div>
                <div class="conversasView">
                    <div class="conversasArquivadas">
                        <span>
                            <i class="fa-regular fa-folder-open"></i>
                            <span id="arquivada">Arquivadas</span>
                        </span>
                        <span id="arquivadasQuant" class="notfy">7</span>
                    </div>

                    <div class="conversasCardGroup">

                        <?php if(1 == 2){?>
                        

                            <div class="conversasCard">
                                <div class="infoPessoal">
                                    <div class="perfilImagem">
                                    <?php if(empty($_SESSION['img'])){?>
                                        <img src="img/perfilNoUser.png">
                                    <?php }else{ ?>
                                        <img src="<?php echo $_SESSION['img'];?>">
                                    <?php }?>
                                    </div>
                                    <div class="PerfilInfo">
                                        <h2 class="UserName">
                                            Roseane
                                        </h2>
                                        <p class="lastMessage">
                                            Certo, meu neném
                                        </p>
                                    </div>
                                </div>
                                <div class="infoNotfy">
                                    <span id="hora" class="nlida">
                                        17:11
                                    </span>
                                    <div class="infoGroup">                                    
                                        <span id="notificacao">
                                            <i class="fa-solid fa-volume-high active"></i>
                                            <!-- <i class="fa-solid fa-volume-xmark active"></i> -->
                                        </span>
                                        <span id="quantMessage" class="nlidaMessage">
                                            5
                                        </span>
                                    </div>
                                </div>
                            </div>
                        <?php }?>

                    </div>
                </div>
            </div>
        </section>
        
        <section class="menuMensagem" style="display: none;">
            <div class="menuPerfil">
                <div class="perfilImagem">
                    <!-- <i class="fa-regular fa-user"></i> -->
                </div>
                <div class="perfilConfig">
                    <ul>
                        <li><i class="fa-solid fa-magnifying-glass"></i></li>
                        <li><i class="fa-solid fa-ellipsis-vertical"></i></li>
                    </ul>
                </div>
            </div>
        </section>
    </main>
    
<script>
    function sendCreate(response){

        if(response != 'Erro'){
            response.forEach(e => {

                let card = document.createElement('div')
                card.classList.add('card')
                card.classList.add('send')

                let infoWrapper = document.createElement('div')
                infoWrapper.classList.add('info-wrapper')

                let imgWrapper = document.createElement('div')
                imgWrapper.classList.add('img-wrapper')

                let img = document.createElement('img')

                if(e[0]['img'] == '' || e[0]['img'] == null){
                    img.src = 'img/perfilNoUser.png'
                }else{
                    img.src = e[0]['img']
                }

                let pessoalInfo = document.createElement('div')
                pessoalInfo.classList.add('pessoalInfo')

                let p1  = document.createElement('p')
                p1.textContent = e[0]['nome'].split(' ')[0]

                let p2  = document.createElement('p')
                let number = e[2].split('-')
                p2.textContent = number[2].slice(0,5) + '-' + number[2].slice(5)

                let icons = document.createElement('div')
                icons.classList.add('icons')

                let i2 = document.createElement('i')
                i2.className = 'fa-solid fa-trash-can'
                i2.id = 'recSolici'
                i2.setAttribute('onclick', `cancelarSolicitacao(${e[1]})`)

                let abbr2 = document.createElement('abbr')
                abbr2.title = 'Cancelar Solicitação'

                abbr2.appendChild(i2)

                icons.appendChild(abbr2)

                pessoalInfo.appendChild(p1)
                pessoalInfo.appendChild(p2)

                imgWrapper.appendChild(img)

                infoWrapper.appendChild(imgWrapper)
                infoWrapper.appendChild(pessoalInfo)

                card.appendChild(infoWrapper)
                card.appendChild(icons)

                $('.cardGroup').append(card)
            });
        }else{
            $('.cardGroup').html('<h2>Nenhuma Solicitação Enviada</h2>')
        }
        
       
    }

    function recieveCreate(response){

        if(response != "Erro"){

            response.forEach(e => {

                let card = document.createElement('div')
                card.classList.add('card')
                card.classList.add('recieve')

                let infoWrapper = document.createElement('div')
                infoWrapper.classList.add('info-wrapper')

                let imgWrapper = document.createElement('div')
                imgWrapper.classList.add('img-wrapper')

                let img = document.createElement('img')

                if(e[0]['img'] == '' || e[0]['img'] == null){
                    img.src = 'img/perfilNoUser.png'
                }else{
                    img.src = e[0]['img']
                }

                let pessoalInfo = document.createElement('div')
                pessoalInfo.classList.add('pessoalInfo')

                let p1  = document.createElement('p')
                p1.textContent = e[0]['nome'].split(' ')[0]

                let p2  = document.createElement('p')
                let number = e[2].split('-')
                p2.textContent = number[2].slice(0,5) + '-' + number[2].slice(5)

                let icons = document.createElement('div')
                icons.classList.add('icons')

                let i1 = document.createElement('i')
                i1.className = 'fa-solid fa-square-check'
                i1.id = 'accSolici'
                i1.setAttribute('onclick', `confirmarSolicitacao(${e[1]})`)

                let i2 = document.createElement('i')
                i2.className = 'fa-solid fa-trash-can'
                i2.id = 'recSolici'
                i2.setAttribute('onclick', `recusarSolicitacao(${e[1]})`)

                let abbr1 = document.createElement('abbr')
                abbr1.title = 'Aceitar Solicitação'

                let abbr2 = document.createElement('abbr')
                abbr2.title = 'Recusar Solicitação'

                abbr1.appendChild(i1)
                abbr2.appendChild(i2)

                icons.appendChild(abbr1)
                icons.appendChild(abbr2)

                pessoalInfo.appendChild(p1)
                pessoalInfo.appendChild(p2)

                imgWrapper.appendChild(img)

                infoWrapper.appendChild(imgWrapper)
                infoWrapper.appendChild(pessoalInfo)

                card.appendChild(infoWrapper)
                card.appendChild(icons)

                $('.cardGroup').append(card)

            });
        }else{
            $('.cardGroup').html('<h2>Nenhuma Solicitação Recebida</h2>')
        }


}
</script>
</html>